package com.isacore.util;

public class PropertyText {

	public static final String PROPERTY_1 = "PROP_1";
	public static final String PROPERTY_2 = "PROP_2";
	public static final String PROPERTY_3 = "PROP_3";
	public static final String PROPERTY_4 = "PROP_4";
	public static final String PROPERTY_5 = "PROP_5";
	public static final String PROPERTY_6 = "PROP_6";
	public static final String PROPERTY_7 = "PROP_7";
	public static final String PROPERTY_8 = "PROP_8";
	public static final String PROPERTY_9 = "PROP_9";
	public static final String PROPERTY_10 = "PROP_10";
	public static final String PROPERTY_11 = "PROP_11";
	public static final String PROPERTY_12 = "PROP_12";
	public static final String PROPERTY_13 = "PROP_13";
	public static final String PROPERTY_14 = "PROP_14";
	public static final String PROPERTY_15 = "PROP_15";
	public static final String PROPERTY_16 = "PROP_16";
	public static final String PROPERTY_17 = "PROP_17";
	public static final String PROPERTY_18 = "PROP_18";
	public static final String PROPERTY_19 = "PROP_19";
	public static final String PROPERTY_20 = "PROP_20";
	public static final String PROPERTY_21 = "PROP_21";
	public static final String PROPERTY_22 = "PROP_22";
	public static final String PROPERTY_23 = "PROP_23";
	public static final String PROPERTY_24 = "PROP_24";
	public static final String PROPERTY_25 = "PROP_25";
	public static final String PROPERTY_26 = "PROP_26";
	public static final String PROPERTY_27 = "PROP_27";
	public static final String PROPERTY_28 = "PROP_28";
	public static final String PROPERTY_29 = "PROP_29";
	public static final String PROPERTY_30 = "PROP_30";
	public static final String PROPERTY_31 = "PROP_31";
	public static final String PROPERTY_32 = "PROP_32";
	public static final String PROPERTY_33 = "PROP_33";
	public static final String PROPERTY_34 = "PROP_34";
	public static final String PROPERTY_35 = "PROP_35";
	public static final String PROPERTY_36 = "PROP_36";
	public static final String PROPERTY_37 = "PROP_37";
	public static final String PROPERTY_38 = "PROP_38";
	public static final String PROPERTY_39 = "PROP_39";
	public static final String PROPERTY_40 = "PROP_40";
	public static final String PROPERTY_41 = "PROP_41";
	public static final String PROPERTY_42 = "PROP_42";
	public static final String PROPERTY_43 = "PROP_43";
	public static final String PROPERTY_44 = "PROP_44";
	public static final String PROPERTY_45 = "PROP_45";
	public static final String PROPERTY_46 = "PROP_46";
	public static final String PROPERTY_47 = "PROP_47";
	public static final String PROPERTY_48 = "PROP_48";
	public static final String PROPERTY_49 = "PROP_49";
	public static final String PROPERTY_50 = "PROP_50";
	public static final String PROPERTY_51 = "PROP_51";
	public static final String PROPERTY_52 = "PROP_52";
	public static final String PROPERTY_53 = "PROP_53";
	public static final String PROPERTY_54 = "PROP_54";
	public static final String PROPERTY_55 = "PROP_55";
	public static final String PROPERTY_56 = "PROP_56";
	public static final String PROPERTY_57 = "PROP_57";
	public static final String PROPERTY_58 = "PROP_58";
	public static final String PROPERTY_59 = "PROP_59";
	public static final String PROPERTY_60 = "PROP_60";
	public static final String PROPERTY_61 = "PROP_61";
	public static final String PROPERTY_62 = "PROP_62";
	public static final String PROPERTY_63 = "PROP_63";
	public static final String PROPERTY_64 = "PROP_64";
	public static final String PROPERTY_65 = "PROP_65";
	public static final String PROPERTY_66 = "PROP_66";
	public static final String PROPERTY_67 = "PROP_67";
	public static final String PROPERTY_68 = "PROP_68";
	public static final String PROPERTY_69 = "PROP_69";

	public static final String PROP_TECHNICAL = "T";
	public static final String PROP_VISUAL = "V";
	
}
